### ISSUE TITLE
Does this gem works with rails 4?

### ISSUE THREAD

**Issue by andrewvmail** [ryanb/nested_form#295]
Does this gem works with rails 4 if so what is required?
From the wiki I can only see instructions for rails 3 and can't find any info from the issues.

Thanks !

**Comment by TheNotary** [comment]
I was having trouble...  I think rails 4 defaults to checking the params in the controller rather than in the model, so the controller should be changed in addition to the other things, and the model shouldn't have attr_accesible, or attr_accessor set for the attributes.  


    # users controller
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :authorization).tap do |whitelisted|
        whitelisted[:problems_attributes] = params[:user][:problems_attributes]
      end      
    end

The gem otherwise works identically.
